containerish/OpenRegistry

- main.go
- registry/v2/registry.go
> Added delete endpoints

- cache/register_for_beta.go
- go.mod
---
dependabot suggestion for security update
> upgraded containerd version to v1.5.4

- registry/v2/registry.go
- Fixed DeleteLayer api to respond with 202 instead of 200
- Total of 49 test cases are passing, 10 failed, 3 skipped
> fixed DeleteLayer api test case

- cache/register_for_beta.go
- cache/store.go
- config/config.go
- main.go
- registry/v2/registry.go
- registry/v2/types.go
- Implemented tag/list api
- Total of 55 cases passing, 4 failing, 3 skipped
> implemented tag/list api

- .github/workflows/go.yml
---
This PR fixes the failing github action issue #19  for OCI Conformance report.
> Fixed OCI Conformance github actions issue

- Dockerfile
- Fixed Dockerfile, included optimised entries to reduce rebuild time and use cache
> fixed Docker file to use cache

- .github/workflows/codeql-analysis.yml
This PR adds a Github Workflow for adding CodeQL Analysis to detect any security vulnerabilities
> Quality Check - Github CodeQL Workflow

- README.md
- Added Github CodeQL Badge to display CodeQL Status
> Doc: added Github CodeQL Badge

- CODE_OF_CONDUCT.md
> doc: added code of conduct

- cache/store.go
- main.go
- registry/v2/registry.go
- registry/v2/types.go
- Implemented delete Manifest and tags through DeleteTagOrManifest api
- Implemented delete blob through DeleteLayer api
> fix: implemented delete apis

- auth/bcrypt.go
- auth/jwt.go
- auth/signin.go
- auth/signup.go
- auth/validate_user.go
- cache/register_for_beta.go
- main.go
- registry/v2/blobs.go
- registry/v2/helpers.go
- registry/v2/registry.go
- registry/v2/types.go
- skynet/skynet.go
- Made code fixes as to comply with golangci linter
> refactor: Linter fix

- .github/workflows/golangci-lint.yaml
- Adding github action for linting checks on pull requests
> chore: adds golangci-lint github action

- registry/v2/registry.go
- telemetry/log.go
> Fix: forward logs to fluent-bit agent

- .github/workflows/conformance.yml
- config/config.go
> Fix: Failing github action for OCI Conformanve

- registry/v2/helpers.go
- registry/v2/registry.go
- router/router.go
- One of the OCI test cases was failing when we tried using redirect to offload bandwidth to client side
- This PR fixes the issue, all the test cases are now passing
> Fix: registry error while redirect

- README.md
This PR Adds four OCI Conformance related badges that let us track each
major functionality individually:
- Push
- Pull
- Content Discovery
- Content Management
> Add: New OCI Conformance Badges

- README.md
> Fix: typo fix in readme

- .github/workflows/oci-dist-spec-content-discovery.yml
- .github/workflows/oci-dist-spec-content-management.yml
- .github/workflows/oci-dist-spec-pull.yml
- .github/workflows/oci-dist-spec-push.yml
- In order for badges to show individual testcases (pull, push, content-management and content-discovery)
> Fix: renamed github workflow names

- .github/workflows/gitguarding.yml
- .github/workflows/oci-dist-spec-content-discovery.yml
- .github/workflows/oci-dist-spec-content-management.yml
- .github/workflows/oci-dist-spec-pull.yml
- .github/workflows/oci-dist-spec-push.yml
- .gitignore
- .pre-commit-config.yaml
- Makefile
- config.yaml.example
Added GitGuardian for Secret Scanning:
- Pre Commit
- Github Actions
- Discord Integration
> Chore: GitGuradian Secret Scanning

- registry/v2/registry.go
- store/postgres/container_image.go
- store/postgres/postgres.go
- store/postgres/queries/registry.go
- types/types.go
- this will help us eliminate multiple api calls from frontend
> Feat: added api to list user catalog with pagination

- README.md
Added the official OCI Certified badge in Readme file
> Chore: OCI Certification Badge

- auth/signup.go
- registry/v2/blobs.go
- registry/v2/registry.go
- removed all but one occurrences of io.ReadAll from the project
- this pr fixes #89 
- the only occurrence is assured to cause no problems since it's reading a request body of a small size, will still work on finding a better solution
> Fix: removed io.ReadAll from entire project

- auth/github.go
- auth/jwt_middleware.go
- auth/renew.go
- auth/sessions.go
- auth/signin.go
- auth/signout.go
- auth/signup.go
- auth/user.go
- go.mod
- registry/v2/blobs.go
- registry/v2/registry.go
> Add: logging for newly merged code

- auth/github.go
> Fix: github redirect

- .github/pull_request_template.md
> add: Pull request template

- MAINTAINERS.md
> add: Maintainers MD

- .github/CODEOWNERS
> add: Code owners

- CONTRIBUTING.md
This PR is to add contribution guidelines
With contribution guidelines in place, there will be a proper structure to contributions made to OpenRegistry and it will also make it easier to review them
> Add: contributing md file

- .github/workflows/dispatch.yml
- .github/workflows/oci-dist-spec-content-discovery.yml
- .github/workflows/oci-dist-spec-content-management.yml
- .github/workflows/oci-dist-spec-pull.yml
- .github/workflows/oci-dist-spec-push.yml
- .gitignore
- Dockerfile
- Makefile
- README.md
- auth/auth.go
- auth/basic_auth.go
- auth/jwt.go
- auth/jwt_middleware.go
- auth/renew.go
- auth/signup.go
- config.yaml.example
- config/config.go
- config/yaml.go
- docs/contributing/development-environment-setup.md
- main.go
- registry/v2/blobs.go
- registry/v2/registry.go
- services/email/email.go
- services/email/sendEmail.go
- services/email/welcome_email.go
Our `config.yaml` is very complex (and long). Even though we can run OpenRegistry without most of the settings, pieces of code still expects values to be present. 
Another thing to notice was that running OpneRegistry locally with TLS was a pain till now. This PR simplifies that
This PR cleans that logic up. We don't use pointers for any `config.OpenRegistryConfig` struct, which defaults the values to empty non-nil values in most cases.
Another thing we change in this PR is using RSA certificates for signing and verifying JWTs. This improves our security posture a bit and this is definitely the better approach than using a secret string.
It's possible to run OpenRegistry locally using TLS certs now. We've added a new doc for it.
> !fix: Auth middleware & Github Actions

- .github/workflows/oci-dist-spec-content-discovery.yml
- .github/workflows/oci-dist-spec-content-management.yml
- .github/workflows/oci-dist-spec-pull.yml
- .github/workflows/oci-dist-spec-push.yml
- config.example.yaml
- config/config.go
- dfs/client/client.go
- dfs/storj/uplink/client.go
- dfs/storj/uplink/options.go
- dfs/storj/uplink/uplink.go
- go.mod
- go.sum
- main.go
Uplink is the native way to interact with Storj. This PR adds an option to use Storj for Storage via Uplink
Closes #255
This PR implements the `DFS.DFS` interface using [storj.io/uplink](https://github.com/storj/uplink).
> feat: Storj integration with Uplink

- auth/sessions.go
- auth/signout.go
- auth/user.go
- vcs/github/github.go
When native fetch sends cookies along with the requests, cookie values are url encoded. That means, `:` becomes `%3A`.
Our `session_id` cookie is in the following format `<random_uuid>:<user_id>`, and when we try to split the session id by `:` to get the user id, we never find it because `:` becomes `%3A`.
This PR adds the logic for url decoding/unescaping because splitting the cooke values, which successfully gives us the user ID from the session ID.
> fix: URL decode before parsing cookies

- .github/workflows/oci-dist-spec-content-discovery.yml
- .github/workflows/oci-dist-spec-content-management.yml
- .github/workflows/oci-dist-spec-pull.yml
- .github/workflows/oci-dist-spec-push.yml
- Makefile
- auth/helpers.go
- auth/jwt.go
- auth/jwt_middleware.go
- auth/renew.go
- auth/reset_password.go
- config.example.yaml
- dfs/filebase/filebase.go
- go.mod
- go.sum
- registry/v2/blobs.go
- registry/v2/context_keys.go
- registry/v2/registry.go
- router/middlewares.go
- router/router.go
Filebase (with IPFS) was failing conformance tests. This was primarily because of invalid presigned url generation
This PR fixes the Presigned url generation for Filebase DFS by adding the required `layers/` prefix to layers identifiers.
> fix: Filebase DFS failing OCI conformance

- go.mod
- go.sum
- health-checks/checks.go
- main.go
- router/router.go
- store/postgres/postgres.go
This PR adds a simple health check at `/health` which primarily monitors the database by pinging it.
This PR adds the `/health` endpoint which returns the response in the following format:
```json
{
"status": "up",
"details": {
"database": {
"status": "up",
"timestamp": "2023-06-19T14:31:18.818247Z"
}
}
}
```
> feat: Add a simple health check for API

- auth/auth.go
- auth/github.go
- auth/helpers.go
- auth/invites.go
- auth/renew.go
- auth/reset_password.go
- auth/server/webauthn_server.go
- auth/signin.go
- auth/signout.go
- auth/signup.go
- auth/token.go
- auth/verify_email.go
- config.example.yaml
- config/config.go
- main.go
- router/router.go
- services/email/createEmail.go
- services/email/email.go
- services/email/sendEmail.go
- services/email/welcome_email.go
- store/postgres/container_image.go
- vcs/github/github.go
- vcs/github/handlers.go
This PR adds a configuration option `webapp.endpoints`, which is an array of urls/endpoints to the clients. These clients are supposed to be websites for now
> feat: Allow multiple clients to access OpenRegistry backend

- auth/invites.go
- auth/reset_password.go
- auth/server/webauthn_server.go
- auth/signin.go
- auth/signup.go
- conformance.vars
- registry/v2/blobs.go
- registry/v2/registry.go
- vcs/github/handlers.go
This PR adds the missing close on request bodies.
The missing close will lead to memory leaking & eventual crash of the program. This PR fixes that.
> fix: Missing body closing after reading

- .github/workflows/oci-dist-spec-content-discovery.yml
- .github/workflows/oci-dist-spec-content-management.yml
- .github/workflows/oci-dist-spec-pull.yml
- .github/workflows/oci-dist-spec-push.yml
> chore: Run OCI GHA on push to main

- .github/workflows/oci-dist-spec-pull.yml
> fix: GitHub actions workflow for OCI Pull

- docs/features/README.md
- docs/features/container-image-analytics.md
- docs/features/grpc-apis.md
- docs/features/oci-extensions.md
- docs/features/organization-mode.md
- docs/features/p2p-container-image-distributon.md
- docs/features/private-container-images.md
- docs/features/vulnerability-scanning.md
> docs: How-to's for new features
