cache/store.go, registry/v2/blobs.go, registry/v2/registry.go
- Removed headers from PullLayer which were causing the fail during OCI tests
- Updated the store.Update() function to overwrite the Manifest.config if the tag is duplicate
- Total of 57 cases are passing, 2 failed, 3 skipped, following the snapshot of same
=> Fix: PullLayer and CompleteUpload for OCI conformance

Dockerfile, cache/store.go, conformance.vars
Wrapped the overflowing int with uint and restricted the numbers of layers within a manifest to be within math.MaxInt16
=> fix: removed int overflow vulnerability

.github/workflows/go.yml, conformance.vars
This PR adds the `OCI_CROSSMOUNT_NAMESPACE` environment variable in the
github action config file. This enables us passing all the test cases.
=> fix: github action for conformance

cache/store.go, main.go, registry/v2/registry.go, registry/v2/types.go
- Addresses #5  
- To list the available repositories
- Uses auth middleware to authenticate the user and returns user's private repositories
- Further modifications to be made when user can access public repos along with their own
=> feat: added catalog api

golangci.yaml
* Enabled following linters apart from default:
- bodyclose
- cyclop
- gochecknoglobals
- goimports
- gosec
- lll
- nilerr
- noctx
- sqlclosecheck
- staticcheck
=> chore: added golangci linter to improve code quality

.github/workflows/golangci-lint.yaml, golangci.yaml
This PR pins the version for `golangci-lint` github action to `v1.42.1` which comes with  support for all the linters we use.
- Runs `make mod-fix` before running linters
- Increased the timeout for linters to `2m`
=> chore: fixes failing linter github action

config/config.go, registry/v2/blobs.go, registry/v2/helpers.go
=> refactor: removed dead code as suggested in issue #42

auth/auth.go, auth/basic_auth.go, auth/signup.go, auth/validate_user.go, main.go, ratelimiter/ratelimiter.go, router/helpers.go, router/route_names.go, router/router.go, telemetry/log.go
- Added auth/basic_auth that contains basic auth functions
- Added telemetry for future logging and metrics purposes
- Added router to contain all the routes and register route functions
=> refactor: refactored to make code more manageable

auth/signup.go, cache/register_for_beta.go
We get the following error when the first user tries to register for beta:
```json
{"error":"unexpected end of JSON input"}
```
This happens because we're trying to unmarshal nil byte slice into a struct with string slice in https://github.com/containerish/OpenRegistry/blob/master/cache/register_for_beta.go#L72
Missing return statement in the if condition above it caused this bug
=> fix: initial user signup fix

cache/register_for_beta.go, main.go, registry/v2/blobs.go, registry/v2/registry.go, router/router.go, telemetry/fluent-bit/fluent_bit.go, telemetry/log.go, types/app_error_keys.go, types/types.go
This PR adds support for using a remote log aggregator using FluentBit.
FluentBit configuration is out of scope for this repo, but we do have a
sample configuration for it. We're currently using JSON formatted logs
with the following template:
```json
{"time":"${time_rfc3339}","request_id":"${request_id}","remote_ip":"${remote_ip}","host":"${host}","method":"${method}","uri":"${uri}","user_agent":"${user_agent}","status":"${status}","error":"${error}","latency":"${latency}","latency_human":"${latency_human}","bytes_in":"${bytes_in}","bytes_out":"${bytes_out}"}
```
Fields Included for logs (For all HTTP requests):
- Timestamp
- RequestID
- RemoteIP
- Host
- Method
- URI
- User Agent
- Status
- Error
- Latency
- Human Latency
- Bytes In
- Bytes Out
If we need, we can add more fields in the …
=> Add: Zerolog with FluentBit  Integration

router/router.go, telemetry/log.go
Adds http request id in logs and response headers
=> Add: HTTP Request ID Middleware

.github/workflows/conformance.yml, registry/v2/registry.go, telemetry/fluent-bit/fluent_bit.go
- Redirecting the Pull operations to offload bandwidth to client side
- For OCI conformance, one of the tests is failing and is being tracked by following issues in OpenContainers:
* https://github.com/opencontainers/distribution-spec/issues/299
* https://github.com/opencontainers/distribution-spec/issues/234
=> Feat: offloading bandwidth to client side for Pull operations

scripts/recreating.sh
- This script will run OpenRegistry and then run OCI-conformance tests against it
=> Chore: added recreating.sh script to replicate the results

go.mod, go.sum, skynet/skynet.go, skynet/types.go
Fixes #79 - from here on we use our fork of skynet maintained at
[Containerish's Fork of Skynet Go SDK](https://github.com/containerish/go-skynet.git)
=> Fix: Use our fork of go-skynet for all Skynet Ops

auth/auth.go, auth/basic_auth.go, auth/jwt_middleware.go, auth/signin.go, auth/signup.go, auth/token.go, main.go, registry/v2/blobs.go, registry/v2/helpers.go, registry/v2/registry.go, registry/v2/types.go, router/router.go, telemetry/log.go, types/app_error_keys.go
- Added new logger struct to contain zerologger and echo logger
- In the earlier implementation, the logger was being called in middleware which caused the log messages to return caller as middelware instead of the handler within which made debugging difficult 
- This PR fixes the issue by removing the middleware and calling logger inside each handler
=> Fix: logging by adding new logger struct

.github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml, .gitignore, Dockerfile, auth/auth.go, auth/jwt.go, auth/jwt_middleware.go, config.yaml, config/config.go, config/yaml.go, main.go, router/router.go, skynet/skynet.go, skynet/types.go, store/postgres/postgres.go, telemetry/fluent-bit/fluent_bit.go
=> Yaml app config

go.mod, go.sum, registry/v2/registry.go
Removed distribution package, since we were only using it for it's sub-package uuid, we're already using google's uuid package so it was redundant
=> Chore: Dependency Cleanup

go.mod, go.sum, registry/v2/blobs.go, registry/v2/registry.go, skynet/skynet.go
=> Refactor: Using Skynet SDK's Metadata API

.github/workflows/golangci-lint.yml, .github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml
Adds Workflow groups and cancels any older action runs when we push consecutively.
This is how it works:
1. Make a change, push and raise a PR, as of now, we run 10 Github Actions.
2. See a typo, or a fix, commit and push before the previous action has passed
3. Now there are 2 simultaneous Github Actions running, out of which, only the newer one matters.
4. This PR cancels the older action that is (are) running and only keeps the latest iteration of it.
=> Chore: Adds cancel-in-progress on consecutive push

db/migrations/000004_create_config_table.up.sql, registry/v2/registry.go, registry/v2/types.go, router/route_names.go, router/router.go, store/postgres/container_image.go, store/postgres/postgres.go, store/postgres/queries/registry.go
- This is the most basic implementation for auto-complete api 
- We are using index with text_pattern_ops
- Optimisations to come as we test and integrate it with frontend
=> Feat: basic implementation for search for auto-completion api

config.yaml.example, config/config.go
config file declares the portal url as:
```yaml
skynet:
portal_url: https://siasky.net
```
but the datatype was declared with tag `skynet_portal_url` which was causing the url defined in the config file to be reset to default always since skynet sdk defaults to `siasky.net` when skynet url is empty
=> Fix: Skynet Portal URL from config file

auth/basic_auth.go, auth/jwt_middleware.go, auth/signin.go, auth/signup.go, auth/token.go, go.mod, go.sum, main.go, registry/v2/blobs.go, registry/v2/helpers.go, registry/v2/registry.go, telemetry/consoleWriter.go, telemetry/log.go
- pretty and readable logging for local debugging
=> Feat: added console writer for local logging

skynet/skynet.go
- moving away from default http client to add timeout and custom http transport
=> Add: updated http client for skynet

registry/v2/extensions/catalog_detail.go, store/postgres/container_image.go, store/postgres/postgres.go, store/postgres/queries/registry.go
=> Add: sort images with namespace and last_updated

auth/auth.go, auth/bcrypt.go, auth/invites.go, auth/jwt.go, auth/jwt_middleware.go, auth/renew.go, auth/reset_password.go, auth/signin.go, auth/signup.go, auth/verify_email.go, config/config.go, router/helpers.go, services/email/createEmail.go, services/email/email.go, services/email/sendEmail.go, services/email/welcome_email.go, store/postgres/postgres.go, store/postgres/queries/users.go, store/postgres/queries/verify_email.go, store/postgres/users.go, types/types.go
this PR fixes #115 
- email service integrated for sending out /invites along with reset password and activate account links
=> Password management apis

config/config.go, config/yaml.go, go.mod
If `OPENREGISTRY_CONFIG` environment variable is set, we can read our configuration from it.
we can export the entire yaml config as an environment variable and it can be parsed as a yaml Go struct now. Super useful for times when we can't mount the config file directly.
=> Add: read configuration from environment variable

config.yaml.example, config/config.go, config/yaml.go, go.mod, go.sum
=> Fix: config validation before starting the service avoids panic

auth/github.go, auth/signin.go, auth/signup.go, auth/verify_email.go, registry/v2/registry.go, router/router.go, store/postgres/users.go, telemetry/fluent-bit/fluent_bit.go
- This PR fixes issue #125 
- Replaced uuid functions with uuid.NewRandom which returns an error along with a random uuid
=> Fix: safe alternative to uuid.New() and uuid.NewString() functions

.github/dependabot.yml, .github/workflows/codeql-analysis.yml
This PR upgrades the version for `CodeQL Github Action` to `v2`. `v1` is deprecated now.
We're also adding dependabot config so that dependabot can take of version bumps of our packages
=> Upgrade CodeQL Github Action

go.mod, go.sum, skynet/skynet.go
In this PR, we bumped the Skynet SDK to use
`v2.0.2-0.20220629062209-f31ff192458d` version. Skynet updated their Pin
Skylink API to return a response body and StatusOk (200) code, previously they
returned NoContent (204) Status Code
=> fix: Bump Skynet SDK

.github/dependabot.yml
At this point, Dependabot has really become a pain. The frequency of PRs is too short.
This PR sets Dependabot interval to a week.
=> chore: Run Dependabot weekly on fridays

.github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml
All of our Github Actions for OCI were uploading their OCI Conformance reports with the same name, which lead to the overwriting of reports uploaded. We only persisted the report of the action the uploaded the file last. This PR fixes that.
We now use unique names for all the reports being uploaded. The filename format is: `oci-distribution-pull-report-${{ steps.vars.outputs.short_commit_hash }}`
The short commit hash is computed using the following command:
```bash
git rev-parse --short HEAD
```
=> fix(ci): Use unique names for OCI report output files

.github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml
It's a pain to debug our CI when something goes wrong. Many times CI fails because of configuration errors or build errors. This PR adds a GitHub Action which can be triggered manually and it let's us SSH into the GitHub Action.
Adds [mxschmitt/action-tmate@v3](https://github.com/mxschmitt/action-tmate). This GitHub action is a conditional step in our OCI GitHub Actions. To trigger this, we need to manually trigger a workflow that we're interested in debugging and by enabling the debug mode
=> add(ci): GitHub Actions debugging

registry/v2/registry.go
The OCI test for slate blob upload was failing for byte size being 1 more than what it should be. We were sending 0-lenght which increases it by one. Updated the bytes 0-{length-1)
Updated byte size for update progress function, OCI test is now passing
`
ctx.Response().Header().Set("Range", fmt.Sprintf("bytes=0-%d", metadata.ContentLength-1))
`
=> fix: Upload progress byte size

auth/jwt_middleware.go
The JWT library that we use (https://github.com/golang-jwt/jwt) recently changed the method of token extraction.
Previously, you could pass the following to the `JWTConfig` and it would work fine:
```go
middleware.JWTConfig {
...
TokenLookup: "cookie:access_token,header:Authorization"
...
}
```
and this would extract the JWT from the Cookie or the Header.
gq
But this is broken in the JWT lib since at least `v4.5.0`
The new method is to also chain the Auth Scheme with the identifier like so:
```go
middleware.JWTConfig {
...
TokenLookup: "cookie:access_token,header:Authorization:Bearer "
...
}
```
> Notice the Bearer has a trailing space, which is required.
This PR adds the Auth Scheme (which is `Bearer` in our case) to the `TokenLookup` field. So the header lookup identifier becomes:
> …
=> fix: JWT parsing in middlewares

.github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml
Some of the environment variables were missing in the github actions for oci tests. This PR adds them.
We add the following required environment variables:
```bash
STORJ_CI_ENDPOINT=${{ secrets.STORJ_CI_ENDPOINT }} yq e -i '.dfs.storj.endpoint = env(STORJ_CI_ENDPOINT)' config.yaml
STORJ_CI_RESOLVER_ENDPOINT=${{ secrets.STORJ_CI_RESOLVER_ENDPOINT }} yq e -i '.dfs.storj.dfs_link_resolver = env(STORJ_CI_RESOLVER_ENDPOINT)' config.yaml
STORJ_CI_LINK_SHARE_SERVICE_ENDPOINT=${{ secrets.STORJ_CI_LINK_SHARE_SERVICE_ENDPOINT }} yq e -i '.dfs.storj.link_share_service = env(STORJ_CI_LINK_SHARE_SERVICE_ENDPOINT)' config.yaml
```
=> fix: Environment variables for OCI Actions

.github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml
OCI Conformance is going through some decisions about how to handle blob mounting from other repositories. Until that's decided we're locking the version to a particular commit where everything is working.
This PR locks the version of OCI Conformance tests to `235fa1b`
=> chore(ci): Lock OCI distribution conformance version

.github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml, config.example.yaml, config/config.go, dfs/client/client.go, dfs/mock/storage.go, go.sum, main.go
This PR adds a mock storage driver for OCI backend. The mock storage implementation uses an in-memory storage provided by [afero](https://github.com/spf13/afero)
The actual storage drivers (like Storj, Filebase, and S3) are all real storage backends & they require some maintenance, like:
1. Provision buckets/resources for CI envirionment
2. Setting policies for automatic deletion for objects
3. Deletion for multipart-aborted uploads
4. Costs
With this **Mock Storage Driver** we don't have to maintain any resources & costs. This is an in-memory storage implementation which gets purged as soon as the app exits.
=> feat(ci): Mock storage

.github/workflows/codeql-analysis.yml, .github/workflows/oci-dist-spec-content-discovery.yml, .github/workflows/oci-dist-spec-content-management.yml, .github/workflows/oci-dist-spec-pull.yml, .github/workflows/oci-dist-spec-push.yml, cmd/registry/registry.go, dfs/client/client.go, dfs/mock/memMappedSystem.go, dfs/mock/mock.go, dfs/mock/mockFileSystem.go, registry/v2/extensions/catalog_detail.go, registry/v2/registry.go
=> fix: Use safe number parsing

auth/server/webauthn_server.go, auth/signup.go, orgmode/admin.go, registry/v2/extensions/analytics.go, registry/v2/extensions/catalog_detail.go, registry/v2/registry.go, registry/v2/repository.go, router/middlewares.go, router/registry.go, router/route_names.go, router/router.go, store/v1/registry/registry_impl.go, store/v1/registry/store.go, store/v1/types/registry.go, store/v1/types/users.go
This feature adds the ability to add a repository to a user's favorite repos list (aka `star a repository`). This can help navigate around OpenRegistry & help the user go through their favorite repositories quickly since those would be (in an ideal case) the repositories a user cares about.
We add two new APIs with with PR:
- `POST /v2/ext/repository/favorite` - Add a repo to your favorites
- `DELETE /v2/ext/repository/favorite` - Remove the repository from your favorites
These APIs update the **user table** as well as the **repositories table**.
- If a repo is starred (added to fav list), the `favorite_count` in repo table is incremented by 1 and user row is updated to include the repo id in their fav list.
- If a repo is unstarred (remove from fav list), then the repo table is updated …
=> feat: APIs to add repositories to favorites and store repo pull count
